remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Blog of a software engineer]
description: [Objects are abstractions of processing. Threads are abstractions of schedule.]