name: CI

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  lint:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-eslint.yml@main
  
  type-check:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-ts-type-check.yml@main

  buildable:
    needs: [lint, type-check]
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nextjs-build.yml@main
    with:
      NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}