name: CI

on:
  pull_request:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-pnpm-setup.yml@main

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
  
  type-check:
    needs: setup
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-ts-type-check.yml@main

  buildable:
    needs: [lint, type-check]
    uses: zhumeisongsong/shared-actions/.github/workflows/reusable-nextjs-build.yml@main
    with:
      NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}